name: Build, Analyze, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure a full repository history for better analysis

      - name: Build and analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install and Run Trivy for File Scanning
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg TMDB_V3_API_KEY=d172688caf4f374ff2a7515a41af1dba -t netflix .
          docker tag netflix jourdancallahan8/netflix:latest
          docker push jourdancallahan8/netflix:latest
        env:
          DOCKER_CLI_ACI: 1

  deploy:
    needs: build-analyze-scan
    runs-on: [aws-netflix]
    steps:
      - name: Pull Docker Image
        run: docker pull jourdancallahan8/netflix:latest

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          scan-ref: 'jourdancallahan8/netflix:latest'

      - name: Deploy Netflix Container
        run: |
          docker stop netflix || true  # Stop the existing container if running
          docker rm netflix || true  # Remove the container if it exists
          docker run -d --name netflix -p 8081:80 jourdancallahan8/netflix:latest
